CREATE INDEX ON :User(name);
CREATE INDEX ON :User(uid);
CREATE INDEX ON :Concept(name);
CREATE INDEX ON :Concept(uid);
CREATE INDEX ON :Context(name);
CREATE INDEX ON :Context(uid);
CREATE INDEX ON :Context(by);
CREATE INDEX ON :Statement(name);
CREATE INDEX ON :Statement(uid);
